name: Discord morning bot

on:
  schedule:
    - cron: '28 11 * * *'  # minute-hour-day-month-weekday UTC
  workflow_dispatch:

jobs:
    wake_up:
        runs-on: ubuntu-latest
        steps:
            - name: Good morning message
              run: |
                curl -X POST -H 'Content-type: application/json' --data '{"content":"Good morning!☀️"}' ${{ secrets.DISCORD_WEBHOOK }}